#!/usr/bin/env node
/*
 * Fills the generated parts of index.html (English) and index.pt.html
 * (Portuguese) from the reference data:
 *
 *  1. Citation lists: <span data-cite-list="QUERY"></span> gets a list of
 *     citation links for every reference matching QUERY. The prose around it
 *     is hand-written; the lists only follow from the data.
 *       QUERY   = clause ("|" clause)*          any clause may match
 *       clause  = term (" " term)*              all terms must match
 *       term    = id=a,b
 *  2. Inline citations: every <a class="cite" data-cite="id">…</a> gets its
 *     label regenerated from the data, e.g. "(An et al., 2024)".
 *  3. The bibliography between the references markers, listing every cited
 *     entry and the section(s) citing it.
 *
 *   node scripts/build-page.js          rewrite both pages
 *   node scripts/build-page.js --check  exit 1 if either page is out of date
 *
 * Fails if the page cites an id that is not in the reference data, or one
 * marked verified: false (its .bib entry is a different paper). Citation lists
 * leave unverified entries out.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PAGES = [
  { file: 'index.html', lang: 'en', citedIn: 'Cited in' },
  { file: 'index.pt.html', lang: 'pt', citedIn: 'Citado em' },
];
const DATA_FILES = ['assets/data/literature.json'];
const START = '<!-- references:start (generated by scripts/build-page.js; do not edit) -->';
const END = '<!-- references:end -->';
const SECTION_PATTERN = /<details class="section" id="([^"]+)">\s*<summary><h2 class="section-title">(.*?)<\/h2>/g;
const CITE_LIST_PATTERN = /(<span class="cite-list" data-cite-list="([^"]+)">)[\s\S]*?(<\/span>)/g;
const INLINE_CITE_PATTERN = /<a class="cite" href="#([^"]+)" data-cite="\1">[^<]*<\/a>/g;
const CITE_PATTERN = /data-cite="([^"]+)"/g;

function escapeHtml(text) {
  return String(text).replace(/[&<>"]/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
  });
}

// ------------------------------------------------------------------- data

function loadReferences() {
  const byId = new Map();
  DATA_FILES.forEach(function (file) {
    const data = JSON.parse(fs.readFileSync(path.join(ROOT, file), 'utf8'));
    data.references.forEach(function (ref) {
      ['id', 'authors', 'year', 'title', 'venue'].forEach(function (key) {
        if (!ref[key]) throw new Error(file + ': reference ' + (ref.id || '?') + ' is missing "' + key + '"');
      });
      if (byId.has(ref.id)) throw new Error('duplicate reference id: ' + ref.id);
      byId.set(ref.id, Object.assign({ verified: true }, ref));
    });
  });
  assignLabels(byId);
  return byId;
}

function surname(author) {
  return author.split(',')[0].trim();
}

// "(An et al., 2024a)"-style labels, with letters when author+year repeat.
function assignLabels(byId) {
  const groups = new Map();
  byId.forEach(function (ref) {
    const a = ref.authors;
    const who = a.length === 1 ? surname(a[0])
      : a.length === 2 ? surname(a[0]) + ' & ' + surname(a[1])
      : surname(a[0]) + ' et al.';
    const base = who + ', ' + ref.year;
    groups.set(base, (groups.get(base) || []).concat(ref));
  });
  groups.forEach(function (refs, base) {
    refs.sort(function (x, y) { return x.title.localeCompare(y.title); });
    refs.forEach(function (ref, i) {
      ref.yearLabel = String(ref.year) + (refs.length > 1 ? String.fromCharCode(97 + i) : '');
      ref.label = base.replace(/\d{4}$/, ref.yearLabel);
    });
  });
}

// --------------------------------------------------------- citation lists

function matchesTerm(ref, term) {
  const [key, value] = term.split('=');
  const wanted = (value || '').split(',');
  if (key === 'id') return wanted.includes(ref.id);
  throw new Error('unknown cite-list term: ' + term);
}

function selectRefs(refs, query) {
  const clauses = query.split('|').map(function (c) { return c.trim().split(/\s+/); });
  const out = Array.from(refs.values()).filter(function (ref) {
    return ref.verified && clauses.some(function (terms) { return terms.every(function (t) { return matchesTerm(ref, t); }); });
  });
  if (out.length === 0) throw new Error('cite-list matched nothing: ' + query);
  return out.sort(function (a, b) { return a.year - b.year || a.label.localeCompare(b.label); });
}

function citeLink(ref, className, text) {
  return '<a class="' + className + '" href="#' + ref.id + '" data-cite="' + ref.id + '">' + escapeHtml(text) + '</a>';
}

function fillCitations(html, refs) {
  const withLists = html.replace(CITE_LIST_PATTERN, function (all, open, query, close) {
    const items = selectRefs(refs, query).map(function (ref) {
      return citeLink(ref, 'cite-item', ref.label);
    });
    return open + '(' + items.join('; ') + ')' + close;
  });
  return withLists.replace(INLINE_CITE_PATTERN, function (all, id) {
    const ref = refs.get(id);
    if (!ref) throw new Error('cited but not in reference data: ' + id);
    if (!ref.verified) throw new Error('cited but not verified: ' + id);
    return citeLink(ref, 'cite', '(' + ref.label + ')');
  });
}

// ----------------------------------------------------------- bibliography

function sectionsOf(html) {
  return Array.from(html.matchAll(SECTION_PATTERN)).map(function (m) {
    return { id: m[1], title: m[2], start: m.index };
  });
}

// id -> [{ id, title } of each section citing it], in page order.
function collectCitations(html) {
  const sections = sectionsOf(html);
  const bibStart = html.indexOf(START);
  const citedBy = new Map();
  for (const match of html.matchAll(CITE_PATTERN)) {
    if (match.index > bibStart && bibStart >= 0) continue;
    const section = sections.filter(function (s) { return s.start < match.index; }).pop();
    if (!section) throw new Error('citation ' + match[1] + ' is outside any section');
    const list = citedBy.get(match[1]) || [];
    if (!list.some(function (s) { return s.id === section.id; })) list.push({ id: section.id, title: section.title });
    citedBy.set(match[1], list);
  }
  return citedBy;
}

function formatEntry(ref, sections, citedInLabel) {
  const details = [ref.volume, ref.issue ? '(' + ref.issue + ')' : '', ref.pages ? ', ' + ref.pages : '']
    .join('').trim();
  const href = ref.doi ? 'https://doi.org/' + ref.doi : ref.link;
  const linkText = ref.doi ? 'doi:' + ref.doi : 'link';
  const link = href ? ' <a href="' + escapeHtml(href) + '">' + escapeHtml(linkText) + '</a>' : '';
  const citedIn = sections.map(function (s) { return '<a href="#' + s.id + '">' + s.title + '</a>'; }).join(', ');
  return [
    '          <li id="' + escapeHtml(ref.id) + '">',
    '            ' + escapeHtml(ref.authors.join(', ')) + ' (' + ref.yearLabel + '). ' + escapeHtml(ref.title) +
      '. <em>' + escapeHtml(ref.venue) + '</em>' + (details ? ' ' + escapeHtml(details) : '') + '.' + link,
    '            <span class="cited-on">' + citedInLabel + ': ' + citedIn + '</span>',
    '          </li>',
  ].join('\n');
}

function fillBibliography(html, refs, citedInLabel) {
  const citedBy = collectCitations(html);
  const missing = Array.from(citedBy.keys()).filter(function (id) { return !refs.has(id); });
  if (missing.length) throw new Error('cited but not in reference data: ' + missing.join(', '));
  const unverified = Array.from(citedBy.keys()).filter(function (id) { return !refs.get(id).verified; });
  if (unverified.length) throw new Error('cited but not verified: ' + unverified.join(', '));
  const entries = Array.from(citedBy.keys()).map(function (id) { return refs.get(id); })
    .sort(function (a, b) { return a.authors[0].localeCompare(b.authors[0]) || a.yearLabel.localeCompare(b.yearLabel); });
  const list = '        <ol class="bibliography">\n' +
    entries.map(function (r) { return formatEntry(r, citedBy.get(r.id), citedInLabel); }).join('\n') + '\n        </ol>';
  const start = html.indexOf(START);
  const end = html.indexOf(END);
  if (start < 0 || end < start) throw new Error('page is missing the references markers');
  return html.slice(0, start + START.length) + '\n' + list + '\n        ' + html.slice(end);
}

// ------------------------------------------------------------------- main

function pageConfig(file) {
  const page = PAGES.find(function (p) { return p.file === file; });
  if (!page) throw new Error('unknown page: ' + file);
  return page;
}

function render(file) {
  const page = pageConfig(file || 'index.html');
  const refs = loadReferences();
  const html = fs.readFileSync(path.join(ROOT, page.file), 'utf8');
  return fillBibliography(fillCitations(html, refs), refs, page.citedIn);
}

function main() {
  const check = process.argv.includes('--check');
  const stale = PAGES.filter(function (page) {
    const next = render(page.file);
    const target = path.join(ROOT, page.file);
    if (next === fs.readFileSync(target, 'utf8')) return false;
    if (!check) fs.writeFileSync(target, next);
    return true;
  });
  if (check && stale.length) {
    console.error(stale.map(function (p) { return p.file; }).join(', ') + ' out of date; run: node scripts/build-page.js');
    process.exit(1);
  }
}

if (require.main === module) main();
module.exports = { PAGES: PAGES, render: render, loadReferences: loadReferences, collectCitations: collectCitations };
